language: php
dist: bionic
sudo: required

matrix:
  include:
    - php: hhvm
      dist: xenial
      env: HHVM=true PHPUNIT=5.7

install:
  - composer install
  - if [[ $HHVM == true ]]; then composer require "symphony/yaml:3.0"; fi
  - if [[ $PHPUNIT == 5.7 ]]; then composer require "phpunit/phpunit:5.7"; fi

before_script:
  - mkdir -p build/logs
  - cd tests

script:
  - |
    if [[ $PHPUNIT == 5.7 ]]; then
      ../vendor/bin/phpunit --colors --coverage-clover ../build/logs/clover.xml .
    else
      phpunit --colors --coverage-clover ../build/logs/clover.xml .
    fi

after_success:
  - cd ..
  - php vendor/bin/coveralls --config .coveralls.yml -v
